# Generated by Django 4.2.7 on 2023-11-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Fruit',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='fruit',
        ),
    ]
