# Generated by Django 4.2.7 on 2023-11-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_rename_movie_fruit_rename_movie_review_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('fruits', models.ManyToManyField(to='fruits.fruit')),
            ],
        ),
    ]
